CREATE TABLE `contacts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(2) NOT NULL,
  `phone` VARCHAR(12) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `dob` VARCHAR(10) NOT NULL,
  `updates` VARCHAR(45) NULL,
  `age` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`id`));